[build]
rustflags = [
    # Clippy lints
    "-W", "clippy::cloned_instead_of_copied",
    "-W", "clippy::map_unwrap_or",
    "-W", "clippy::redundant_closure_for_method_calls",
    "-W", "clippy::unnested_or_patterns",
    "-W", "clippy::uninlined_format_args",
]
[target.x86_64-unknown-linux-musl]
    rustflags = ["-C", "target-feature=+crt-static"]
[target.aarch64-unknown-linux-musl]
    rustflags = ["-C", "target-feature=+crt-static"]
[target.armv7-unknown-linux-musleabihf]
    linker = "arm-linux-gnueabihf-gcc"
